backend:
  name: github
  repo: yejing195352-sudo/yejing195352-sudo.github.io
  branch: main
  auth_type: pkce
  app_id: 1995616

media_folder: "source/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "我的文章"
    folder: "source/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "文章标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "分类", name: "categories", widget: "string", required: false }
      - { label: "标签", name: "tags", widget: "list", required: false }
      - { label: "正文内容", name: "body", widget: "markdown" }


# 定义内容集合，这里我们只定义“文章”
collections:
  - name: "posts" # 集合的唯一标识符
    label: "我的文章" # 在CMS界面上显示的名称
    folder: "source/_posts" # 文章的.md文件实际存储的文件夹
    create: true # 允许在CMS中创建新文章
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # 生成文件名的规则
    fields: # 定义文章编辑器中的字段
      - { label: "文章标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "分类", name: "categories", widget: "string", required: false }
      - { label: "标签", name: "tags", widget: "list", required: false }
      - { label: "正文内容", name: "body", widget: "markdown" }